package com.sofi.coupons.enums;

public enum Category {

	SPORTS, VACATION, FOOD, VIDEO_GAMES, FOR_KIDS, TECHNOLOGY, MUSIC_AND_FESTIEVALS, 
	FOR_PETS, CLOTHING_AND_ACCSESSORIES, CINEMA_AND_THEATRE, HYGIENE;


}
